routes/web.php
<?php

use App\Http\Middleware\CheckAdmin;

Route::get('register', 'Access\RegisterController@getRegister')->name('register');
Route::post('register', 'Access\RegisterController@postRegister');
Route::get('login', 'Access\LoginController@getLogin')->name('login');
Route::post('login', 'Access\LoginController@postLogin');
Route::get('logout', 'Access\LogoutController@getLogout')->name('logout');

Route::get('show/{id}','HomeController@show');

Route::resource('comments','CommentController');

Route::resource('posts', 'PostController');
Route::get('index', 'HomeController@index');
Route::post('posts/{id}','PostController@edit');

Route::post('search', 'PostController@search');

Route::resource('users', 'UsersController')->middleware(CheckAdmin::class);
Route::post('users/update', 'UsersController@update')->middleware(CheckAdmin::class);

Route::get('/', function () {
    return redirect()->action('HomeController@index');
});

Route::get('admin', function () {
    return redirect()->action('UsersController@index');
});

Route::get('user', function () {
    return redirect()->action('PostController@index');
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

resources/views/action_button.blade.php
<div style="min-width: 150px;">
    <a href="javascript:void(0)" data-toggle="tooltip" data-id="{{ $id }}" data-original-title="Edit" class="edit btn btn-success edit-user">
        Edit
    </a>
    <a href="javascript:void(0);" id="delete-user" data-toggle="tooltip" data-original-title="Delete" data-id="{{ $id }}" class="delete btn btn-danger">
        Delete
    </a>
</div>

resources/views/post_paragraph.blade.php
@if ($posts != null)
    @foreach ($posts as $post)
    <div class="post-paragraph col-4 mt-2" id="post-paragraph-{{ $post->id }}">
        <div class="row p-1" style="height:auto;width:100%;background:#DCDCDC">
        @if (auth()->check())
            @if (auth()->user()->id == $post->user_id)
            <div class="col-12 text-right">
                <button class="edit-post-btn fas fa-edit" id="edit_post" data-toggle="modal" data-target="#formModalEditPost" data-id="{{ $post->id }}"></button>
                <button class="delete-post-btn fas fa-trash" data-toggle="modal" data-target="#confirmDelPost" data-id="{{ $post->id }}"></button>
            </div>
            @endif
        @else
            <div class="col-12 text-right" style="height:21px">
                
            </div>
        @endif
            <a class="row m-1" style="text-decoration: none" href="show/{{$post->id}}">
                <div class="col-5">
                    <img width="100px" height="100px" style="background-position: center center;background-size:cover;" src="{{asset('images/'.$post->image)}}">
                </div>
                <div class="col-7 " style="background:white;height:100px">
                    <div class="row" >
                        <div class="col-12" style=" white-space: nowrap; height:30px;width:80px;overflow:hidden;text-overflow: ellipsis; ">
                            Title : {{$post->title}}
                        </div>
                        
                        <div class="col-12" style=" white-space: nowrap; height:30px;width:80px;overflow:hidden;text-overflow: ellipsis; ">
                            Content : {{$post->content}}
                        </div>
                        <div class="col-12" style=" font-size:10px;white-space: nowrap; height:15px;width:80px;overflow:hidden;text-overflow: ellipsis; ">
                            Create by : {{$post->user['username']}}
                        </div>
                        <div class="col-12" style=" font-size:10px;white-space: nowrap; height:15px;width:80px;overflow:hidden;text-overflow: ellipsis; ">
                            Create at : {{$post->created_at}}
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    @endforeach
    <div class=" col-12 pagination justify-content-center mt-3">
        {{ $posts->appends(request()->input())->links() }}
    </div>
@else
<div>
    <p colspan="7" style="text-align: center">Can't find this Post</p>
</div>
@endif

resources/views/post_table.blade.php
@if ($posts != null)
    <table class="table table-hover text-center table-bordered" id="post_datatable">
        <thead>
            <tr>
                <th>No</th>
                <th>ID Post</th>
                @if(auth()->user()->level == 'admin')
                <th>Owners</th>
                @endif
                <th>Title</th>
                <th>Content</th>
                <th>Created at</th>
                <th>Action</th>
            </tr>
        </thead>
        <input id="selected-row-id" type="hidden" value="">
        <input id="last-row-id" type="hidden" value="{{ $posts->total() }}">
        <input id="page-number" type="hidden" value="{{ 9 * ($posts->currentPage() - 1) }}">
        <tbody id="post-table-body">
            @php
                $number = 9 * ($posts->currentPage() - 1)
            @endphp
            @foreach ($posts as $key => $post)
            <tr id="post-row-{{ $post->id }}">
                <td id="post-id-{{ $post->id }}" data-id="{{ $key + 1 + $number }}"> {{ $key + 1 + $number }} </td>
                <td> {{$post->id}} </td>
                @if(auth()->user()->level == 'admin')
                <td> {{$post->user['username']}} </td>
                @endif
                <td> {{$post->title}} </td>
                <td> 
                    <textarea style="max-width:100%; max-height:100px; border:none" readonly>{{$post->content}}</textarea>
                </td>
                <td> {{$post->created_at}} </td>
                <td>
                    <a id="show_post" href="{{route('posts.show',$post->id)}} " class="btn btn-success show-post-btn" data-toggle="modal" data-target="#formModalShowPost" data-id="{{ $post->id }}"><i class="fas fa-eye"></i></a>

                    <a id="edit_post" class="btn btn-warning edit-post-btn" data-toggle="modal" data-target="#formModalEditPost" data-id="{{ $post->id }}"><i class="fas fa-edit"></i></a>

                    <button class="btn btn-danger delete-post-btn" data-id="{{ $post->id }}" data-toggle="modal" data-target="#confirmDelPost"><i class="fas fa-trash"></i></button>

                    <a id="view" href="" class="btn btn-primary" data-id="{{ $post->id }}"><i class="fas fa-expand"></i></a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pagination justify-content-center">
        {{ $posts->appends(request()->input())->links() }}
    </div>
@else
<tr>
    <td colspan="7" style="text-align: center">Can't find this Post</td>
</tr>
@endif